# Generated by Django 3.2.16 on 2022-12-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='NIP',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_club',
            field=models.BooleanField(default=False),
        ),
    ]
