# Generated by Django 3.2.16 on 2022-12-08 15:35
import os

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.create(name=os.environ.get('DJ_GROUP_PLAYERS'))
    Group.objects.create(name=os.environ.get('DJ_GROUP_CLUBS'))


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.create(name=os.environ.get('DJ_GROUP_PLAYERS')).delete()
    Group.objects.create(name=os.environ.get('DJ_GROUP_CLUBS')).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_addfields'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
