# Generated by Django 3.2.16 on 2023-02-14 15:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='NIP',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
