# Generated by Django 3.2.16 on 2022-12-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(max_length=12),
        ),
    ]
