# Generated by Django 3.2.16 on 2024-03-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20240312_1719"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="NIP",
            new_name="nip",
        ),
    ]
