# Generated by Django 3.2.16 on 2022-12-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=35)),
                ('quantity', models.IntegerField()),
                ('multisport', models.IntegerField(choices=[(1, 'Akceptuje'), (2, 'Nie akceptuje')])),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.IntegerField(choices=[(1, 'grass'), (2, 'clay'), (3, 'hard')])),
                ('preference', models.IntegerField(choices=[(1, 'inside'), (2, 'outside')])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.court')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=35)),
                ('price', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club')),
            ],
        ),
    ]
