# Generated by Django 3.2.16 on 2022-12-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='club',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='weekdays',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='weekend',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='court',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='club.court'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='cost',
            field=models.IntegerField(choices=[(70, '6-10'), (60, '10-14'), (80, '14-22')]),
        ),
    ]
