# Generated by Django 3.2.16 on 2023-01-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='finish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
