# Generated by Django 3.2.16 on 2024-03-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_initial"),
        ("reservation", "0002_reservation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="club.coach",
            ),
        ),
    ]
