# Generated by Django 3.2.16 on 2022-12-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='finish',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.CharField(max_length=30),
        ),
    ]
