# Generated by Django 3.2.16 on 2022-12-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_user'),
        ('reservation', '0003_auto_20221216_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.club'),
        ),
    ]
